### ISSUE TITLE
Headers aren't rendered

### ISSUE THREAD

**Issue by dbkblk** [BearToCode/carta#101]
Hi,
I've integrated carta into by svelte component and it doesn't render bold on headers. What am I doing wrong ?

```
let carta = new Carta();
let content = '';

<MarkdownEditor {carta} value={content} />
```

![Screenshot 2024-07-10 at 08-19-31 Association Le Petit Prince](https://github.com/BearToCode/carta/assets/2344816/1328641f-fda7-42ea-9463-1601133d8098)

**Comment by BearToCode** [comment]
You need to provide a [stylesheet](https://beartocode.github.io/carta/editing-styles#markdown-stylesheets): headers are rendered correctly, but since no styling is applied they look like normal text.

**Comment by dbkblk** [comment]
Thank you for your help, I realized that it might be that because marked rendering is having the same issue.
