### ISSUE TITLE
BUG - Cursor disappears when pressing backspace

### ISSUE THREAD

**Issue by philmas** [BearToCode/carta#104]
I have a Carta component like so:

```
<MarkdownEditor {carta} bind:value={markdown} mode="tabs" />
```

On my webpage pressing backspace several times makes my cursor disappear. I have to reclick the component to be able to interact again.

**Comment by BearToCode** [comment]
The issue is related to changes I recently made, and seems to occur only on mobile. Try updating to the latest version published today and see if it is still there.

**Comment by Codebelife** [comment]
facing the same issue with the latest version of carta also

**Comment by BearToCode** [comment]
@Codebelife what device are you using? Does this also happen on the docs [examples](https://beartocode.github.io/carta/examples)?

**Comment by BearToCode** [comment]
Should be fixed in the newest version about to be published. Let me know if you still experience the issue!
