### ISSUE TITLE
Split toggle mode

### ISSUE THREAD

**Issue by zFlxw** [BearToCode/carta#106]
hey there,
I thought it would be nice to have the ability for a split toggle mode (so basically a split mode, but you can disable the split preview). I just wanted to ask if this is not implemented by choice or if there was just nobody who needed that?

**Comment by BearToCode** [comment]
Hi, I'm not sure I understand what you suggest. Do you mean like a button to switch from split or tabs?

**Comment by zFlxw** [comment]
Kind of. So basically what I was thinking is a button to enable or disable the split view (but while disabled, only the code is shown and there is no preview tab)

**Comment by BearToCode** [comment]
Mhhh... I guess you want to do something like the "Discord" example, right? I guess in that case you could [disable the whole toolbar](https://beartocode.github.io/carta/api/core#disabletoolbar) or, if you just want to remove the preview tab, you could set `display: none` on the buttons styles.

**Comment by zFlxw** [comment]
Acutally, what I want to implement is more along the lines of VSCode, for example. If you look at the top right corner of the screenshot, there is this "toggle" button, and when you click it, the rendered preview shows (screenshot two)

![image](https://github.com/user-attachments/assets/c73a62a9-15d9-466d-9a9b-c2afd6af7c5d)

![image](https://github.com/user-attachments/assets/89b5ac12-8b1c-4f0a-a0d3-3d9d105235c4)

**Comment by BearToCode** [comment]
Undestood! I guess you could try extending the editor, providing a new [icon](https://beartocode.github.io/carta/api/extension#icons) that when pressed toggles between having `split` mode and `tabs` mode. Then you can remove the tabs buttons by setting `display: none`. You can also use a button outside the editor instead of embedding an icon.

**Comment by zFlxw** [comment]
Sounds like a suitable solution, thanks!
