### ISSUE TITLE
Markdown not rendered correctly.

### ISSUE THREAD

**Issue by zFlxw** [BearToCode/carta#107]
Hey,
I am storing the markdown code - which the user enters inside the MarkdownEditor - inside my database (I store the `value` field of the `MarkdownEditor` component) and then re-render it with the Markdown component in another part of my application. However, this does not work as expected.

Below is a screenshot of how the markdown gets rendered by the `Markdown` component:

![image](https://github.com/user-attachments/assets/1d633285-cba2-4272-a3c2-87c9845abd22)

As you can see, the headings are not rendered correctly and line breaks are also not rendered. Here is the code I used to render this content:

```svelte
<script lang="ts">
  import { createCartaEditor } from '$lib/components/editor/carta';
  import type { Card } from '$lib/types/entities/card.types';
  import { Markdown } from 'carta-md';
  import '$lib/styles/card_editor.scss';

  export let card: Card;

  const markdownRenderer = createCartaEditor();
</script>

<div>
  <Markdown carta={markdownRenderer} bind:value={card.frontSide} />
</div>
```

My `createCartaEditor()` function is defined as:
```ts
import { FunctionSquare } from 'lucide-svelte';
import { code } from '@cartamd/plugin-code';
import { math } from '@cartamd/plugin-math';
import DOMPurify from 'dompurify';
import { Carta } from 'carta-md';

export function createCartaEditor() {
  const editor = new Carta({
    sanitizer: DOMPurify.sanitize,
    theme: 'material-theme-darker',
    extensions: [math(), code()],
  });

  editor.icons.push({
    id: 'formular',
    action: (input) => input.toggleSelectionSurrounding('$$'),
    component: FunctionSquare,
  });

  return editor;
}
```

**Comment by BearToCode** [comment]
Hi,
I cannot tell much from just that screenshot, but it looks like the endline characters(`\n`) have been escaped, so everything became just one big line. Maybe it has something to do with how you upload/retrieve data from your database? Can you provide the string you are using?

Sidenote: you should create your own extension with the icon instead of using `editor.icons.push`.

**Comment by zFlxw** [comment]
Hey,
sorry for the delay. I figured out that the line breaks are probably related to how the value is stored by the editor. This was pretty easy to fix, just by replacing all `\\n` with an actual line break (`\n`).

However, there is still an error with rendering KaTeX. The following markdown code:
```md
Given the function\n$$ f(x)=\\dfrac{1}{2}x^2+5x $$,\ncalculate the zeros.
```
produces this outcome:
![image](https://github.com/user-attachments/assets/8986fbbe-31f1-4f25-86de-df1dacf13f87)
