### ISSUE TITLE
Dont conditionally render input on tab change

### ISSUE THREAD

**Issue by Specy** [BearToCode/carta#111]
Trying out the editor when switching to/from the write and preview, going back to Write, the syntax highlight for the editor flickers because it is getting mounted conditionally when the tab is selected. It makes sense to conditionally render the markdown content as it could lag while typing, but the input should always be rendered, just kept hidden (display:none) 

https://github.com/BearToCode/carta/blob/1a15159e41e7de7432c645db11f7793d27dcf61d/packages/carta-md/src/lib/MarkdownEditor.svelte#L170

Here it should just toggle display none on a wrapper element (or Input itself)

**Comment by BearToCode** [comment]
Thanks for the report. Just to let you know I won't be able to work on this for the following days, but I'll check it out once I get some time.

**Comment by Specy** [comment]
Sure! I've made a MD editor in the past, If I find anything to improve I'll make an issue, I'd do the PRs myself just wanted confirmation on the ideas before implementing them

**Comment by BearToCode** [comment]
Hi again! I created a simple PR that should fix the issue #116. If you want you can check it out :)

**Comment by Specy** [comment]
I left a comment there

**Comment by BearToCode** [comment]
On the PR? I can't find it...

**Comment by Specy** [comment]
Ah weird, didn't know that reviews were only visible to me, I made an actual comment now

**Comment by Specy** [comment]
Very nice! Now the editor feels much more snappy
