### ISSUE TITLE
[plugin-component] component is not rendering sometimes

### ISSUE THREAD

**Issue by maisonsmd** [BearToCode/carta#112]
When I tried out plugin-component example, the H1 component flickered as I was typing (see video).

https://github.com/user-attachments/assets/08e2d428-03c6-41fa-b292-f9cf547feee9

Reproduction path:
- Clone Carta repo
- `pnpm build`
- `cd packages/plugin-components`
- `pnpm dev`

Expected result:
- Unedited lines should stay persistently in the preview panel.

**Comment by BearToCode** [comment]
Thanks for the report. Just to let you know, I won't be able to work on this for the following days, but I'll check it out once I get some time.

**Comment by BearToCode** [comment]
Ok, I figured it out! It wasn't easy to understand why it did this but the fix was easy :)
