### ISSUE TITLE
Possible write/edit in rendered mode?

### ISSUE THREAD

**Issue by drloloto** [BearToCode/carta#113]
Is it possible to write text in rendered mode?

**Comment by BearToCode** [comment]
Can you explain a bit more? If you want to be able to edit the renderer HTML directly you would need a WYSIWYG (what-you-see-is-what-you-get) editor. They are quite more complex. You can find them online :)

**Comment by drloloto** [comment]
> Can you explain a bit more? If you want to be able to edit the renderer HTML directly you would need a WYSIWYG (what-you-see-is-what-you-get) editor. They are quite more complex. You can find them online :)

Ahh thanks, now I understand the scope of the library :)

**Comment by HuakunShen** [comment]
Is there any plan for this library to become WYSIWYG?
These editor libraries are usually in react, like https://platejs.org/

**Comment by BearToCode** [comment]
> Is there any plan for this library to become WYSIWYG? These editor libraries are usually in react, like https://platejs.org/

WYSIWYG editors work way differently, and they are way more complex. I do not see Carta being able to achieve that. I built it with the focus of keeping it simple, and easily extendable, which is not really the case with those editor.

For you interest, I've heard that [TipTap](https://tiptap.dev/) works great even with Svelte, and it supports several frameworks.
