### ISSUE TITLE
feat: Improve PreRendered component

### ISSUE THREAD

**Issue by ieedan** [BearToCode/carta#124]
First of all this library is awesome.

I have run into one main issue when I am using it though.

For instance say I have a bunch of posts that I want to render in preview on a page:
```ts
export const load = () => {
    const posts = db.posts(); // just an example
    
    return {
        posts
    } 
}
```

The issue is that when it gets to the page and I need to render it I haven't prerendered the content of the post. 

I could add a property on post to add the rendered content too but thats not so great. A better way would be to just individually render the content on the client. The docs unfortunately don't give a lot of guidance for situations like this. 

The solution I have come to is to do something like this:
```svelte
<!-- Start rendering -->
{#await carta.render(post.content)}
    <!-- While rendering -->
    {@html carta.renderSSR(post.content)}
{:then html}
    {@html html}
{/await}
```

This will immediately render the content of the page while waiting for shiki to finish highlighting. Whenever shiki is done it will render the full content.

It may be benificial to add some guidance for this or to actually include it in the `PreRendered` component the implementation looking something like this:
```svelte
<script lang="ts">
	export let html: string;
	export let theme = 'default';
        export let render: boolean = false;
        export let carta: Carta | undefined = undefined;
</script>

<div class="carta-viewer carta-theme__{theme} markdown-body">
    {#if render && carta}
        {#await carta.render(html)}
            {@html carta.renderSSR(html)}
        {:then final}
            {@html final}
        {/await}
    {:else}
        {@html html}
    {/if}
</div>
```

Let me know what you'd think if it makes sense I can open a PR!

**Comment by BearToCode** [comment]
Hi! What you've done here is basically the same thing of what the `<Markdown>` component does. The `<PreRendered>` component accepts HTML, not Markdown. You can read about it [here](https://beartocode.github.io/carta/getting-started#pre-rendering).

What I've done myself in a similar situation is to add a field `html` to `Post`, which in my case corresponds to a column in the db where I store the data. Then, every time I update the post content, I also make sure to render it and add it to that field. This way, it is only rendered one time, and both the server response and the client are faster. You need to use `<PreRendered>` for that.

**Comment by ieedan** [comment]
Yeah I just don't care for the html field for a few reasons. 

1. It doubles your row size (if the content will need to be edited later)
2. If you aren't using a JS backend there is no `carta` for rendering on insert which forces you to make sure both fields are up to date on the client before sending to the server

In any case the `Markdown` component does exist.
