### ISSUE TITLE
HTML syntax not working

### ISSUE THREAD

**Issue by Pasithea0** [BearToCode/carta#126]
I would like to use HTML syntax inside the editor for custom styles. However, nothing shows up.

<img width="1497" alt="Screenshot 2024-10-20 at 12 02 26 PM" src="https://github.com/user-attachments/assets/ba7a24db-4da7-431d-82cc-4fc88f79891c">

Any idea how to get this working?

**Comment by Pasithea0** [comment]
Forgive my stupidity, but I'm still having trouble getting this working. If you can show me where to use `.use(remarkRehype, { allowDangerousHtml: true })` it would be a great help. Take your time and thanks

**Comment by BearToCode** [comment]
This should work:

```ts
const carta = new Carta({
    rehypeOptions: { allowDangerousHtml: true },
    sanitizer: false
});
```

**Comment by Pasithea0** [comment]
ahh its in the carta const. Thanks
