### ISSUE TITLE
Rendering Error - list + checkbox

### ISSUE THREAD

**Issue by sebadob** [BearToCode/carta#133]
Hey,

I am not sure if I need to set some config option, but I get a rendering issue for 

```
- [ ] item 1
- [ ] item 2
- [ ] ...
```

When I try to render such a list with checkboxes, each line is splint into multiple ones with very werid spacing, while the checkbox uses its own full line. I stumbled about this when trying to render the [Rauhy README.md](https://github.com/sebadob/rauthy/blob/main/README.md) for testing. It looks like so:

![grafik](https://github.com/user-attachments/assets/25580c72-1c14-487e-b414-3dc9214efeb6)

while it should look like:

![grafik](https://github.com/user-attachments/assets/bdad8f77-8b3a-44dd-82fb-3c63bb48aba8)

I tried to fix this with CSS on the wrapping container, but without any luck.

**Comment by BearToCode** [comment]
Hello,
This looks like an issue with the CSS you are using for rendering the list. From experience, it looks like the `display` property of every `li` element is not properly set, but it's impossible to say without using the browser inspector. Unless the rendered HTML structure is wrong, it does not have to do with the library.

**Comment by sebadob** [comment]
> (..) it does not have to do with the library

Okay, thanks!

Maybe some global `li` css then.
I will have a look and figure this out.

Sorry for bothering you.

**Comment by BearToCode** [comment]
No problem at all! Have a nice day

**Comment by sebadob** [comment]
Fyi, it was a `width: 100%` for `input` in the global css.

I really like this project! Thanks for your work!
