### ISSUE TITLE
How to enable spell check

### ISSUE THREAD

**Issue by gagan-bansal** [BearToCode/carta#134]
At two places in [the code](https://github.com/search?q=repo%3ABearToCode%2Fcarta%20spellcheck&type=code), spellcheck has been mentioned but I could not enable. Can you please let me know how to enable spell check in editor,

**Comment by BearToCode** [comment]
You're right, the spellcheck couldn't be set. I just fixed it, you just need to update to the version about to be published. Thanks for pointing that out!

```svelte
<MarkdownEditor
  textarea={{ spellcheck: true }}
    // ...
/>
```

**Comment by gagan-bansal** [comment]
Thank you David, it is a simple and nice project. I am going to use it in one of my project, if found any issue, I'll report the same.
