### ISSUE TITLE
Tailwindcss integration / implementation

### ISSUE THREAD

**Issue by philmas** [BearToCode/carta#14]
First of all, thank you for this markdown editor. It looks very promising.

You mention in your Readme that it can be configured with tailwind typography. I would like to know how to do this best, especially for the previewing.

Perhaps anyone of you can assist?

**Comment by BearToCode** [comment]
Hi! Thanks for the kind words.

[Tailwind Typography](https://tailwindcss.com/docs/typography-plugin) is a plugin that adds default styles for HTML elements whose classes you cannot directly change. It was mentioned in the README as an example of a premade complete markdown stylesheet.
If you meant to use custom tailwind rules in the generated HTML I think the best way is to use the `@apply` rule of postcss, [here](https://tailwindcss.com/docs/typography-plugin) is a guide from their docs.

Let me know if you have any doubt.

**Comment by mispp** [comment]
i think this should be added somewhere to the guide.

in any case, to add maybe an obvious thing here if someone searches for it, i had the same issue only i needed it also for switching it based on light/dark theme with tailwind, do this:

```css
@media (prefers-color-scheme: dark) {
    .markdown-body {
        @apply prose-invert;
    }
}

@layer base {
    .markdown-body {
        @apply prose;
    }
}

```
