### ISSUE TITLE
Support internationalization of interface components

### ISSUE THREAD

**Issue by ottonomy** [BearToCode/carta#21]
Thanks for the library. I found it from a comment you left on a Reddit [thread](https://www.reddit.com/r/sveltejs/comments/12axr97/good_markdown_editor_for_sveltekit/). It was easy to incorporate into my SvelteKit app. I like the scope of what you've chosen to take on here, and the UX is pretty nice.

I'm offering an internationalized app with multiple translations, but using the tabbed interface, I see that the tab names "Write" and "Preview" are hard coded. Could you support passing in an optional dictionary of strings for these and any other strings that appear in the interface? 

If you like the idea, I'd be happy to contribute a PR. Might take me until after the December holidays to get to it though.

**Comment by BearToCode** [comment]
Hi! I created a simple PR that add the option to customize the labels you mentioned. You can check it out and tell me if that's ok for you.

**Comment by BearToCode** [comment]
I'm gonna merge that for now and mark the issue as completed. Feel free to reopen it/open another for other issues.

**Comment by ottonomy** [comment]
Thanks for adding the feature while I was out on vacation. Works great. Here's how it looks in my app, when the french translation is active:

<img width="581" alt="Screenshot 2024-01-03 at 10 04 31 AM" src="https://github.com/BearToCode/carta/assets/2304883/f939d4b1-6f17-43ca-9b19-c8f64ac9513c">

I may put in a PR to add the ARIA labels to the list of customizable labels, but this is great. I don't often use third party UI components because of the need to do precise customizations, but this editor worked out well, and you're on top of issues. Thanks again!

**Comment by BearToCode** [comment]
Glad you liked it! Thanks for the kind works :)
