### ISSUE TITLE
Support screen reader labels for toolbar icon buttons

### ISSUE THREAD

**Issue by ottonomy** [BearToCode/carta#22]
It would be nice to add a `.sr-only` class (see [for example](https://tailwindcss.com/docs/screen-readers)) with a label for each of the buttons in the toolbar so that it is sensible for non-visual users. Keyboard navigation is clean so far but without screen reader content, somebody tabbing through all the buttons would be a little lost before they get to the actual textarea.

GitHub's editor box that I'm typing this issue into uses arrow keys within the toolbar for navigation and uses tab to go between button groups only. That might be a nice enhancement, but it might increase the complexity a bit much.

**Comment by BearToCode** [comment]
Hello again,
it would be nice to improve editor accessibility, but I think more changes would need to be done:
- group editor buttons into groups, like on GitHub(as you mentioned),
- add aria-labels to buttons, maybe making them customizable,
- change <tab> behavior in the editor.

I'm no expert in accessibility, so, while I know how to approach the last two, I have no clue on how to group various elements and make them navigable through arrows key. Do you know how to do that?
