### ISSUE TITLE
Customize `<textarea>` `name` attribute

### ISSUE THREAD

**Issue by darrylyeo** [BearToCode/carta#26]
I'm using `<CartaEditor>` within a `<form>` and would like to customize the `formData` entry name to be different than `"md"`. Can there be a way to specify a custom  `name` attribute?

https://github.com/BearToCode/carta/blob/4075b8a76f0529ed1e1143f70d8907cf388dbdb3/packages/carta-md/src/lib/internal/components/MarkdownInput.svelte#L59-L60

**Comment by BearToCode** [comment]
Hello,

with the PR I linked you'll be able to do the following:

```svelte
<CartaEditor {carta} textarea={{
  name: "my-name"
}} />
```

**Comment by darrylyeo** [comment]
Awesome, that was quick! 🎉
