### ISSUE TITLE
Support for Svelte 5

### ISSUE THREAD

**Issue by jsorb84** [BearToCode/carta#29]
Hi there, recently updated to SvelteKit 2 and also using Svelte 5 with runes mode enabled, seems to break the package and I am unable to get it working.

**Comment by BearToCode** [comment]
Hi, 
can you describe your problem more accurately? I've tried setting up a new SvelteKit app with Svelte5 and the editor seems to be working just fine (I had to use `-f` while installing to prevent peer deps warnings). If the problem was just the peer dependency, I can easily fix that.

**Comment by jsorb84** [comment]
I did a fresh install of Svelte and tried again and it's working fine now, my apologies..
