### ISSUE TITLE
markdown styling

### ISSUE THREAD

**Issue by jobidon** [BearToCode/carta#30]
Just getting started with carta and after installing the main package and a couple of plugins in a sveltekit project, I tried to render a very simple md paragraph, and noticed that `<li>` don't have a bullet points by default. The text shows up fine, but there is no bullet before it.
I suspect that a stylesheet needs to be included, but by default, the bullet points are not present. So I tried including/removing the css included in the plugins, as well as `"@tailwindcss/typography"` but the  problem remains.
The example page does show the bullet points, so I suspect this is just a basic omission on my part, but could you let me know what I'm missing?
Or is there a `list-style-type` directive I need to include elsewhere?
Here's what I have:
```
	import { Carta, CartaEditor, CartaViewer } from 'carta-md';
	import { emoji } from '@cartamd/plugin-emoji';
	import { slash } from '@cartamd/plugin-slash';
	import { code } from '@cartamd/plugin-code';
	import 'carta-md/default.css'; /* Default theme */
	import 'carta-md/light.css'; /* Input theme */
	import '@cartamd/plugin-emoji/default.css';
	import '@cartamd/plugin-code/default.css';
```
and I include the component like this: 
```
<CartaEditor {carta} bind:value mode="tabs" placeholder="sample text"></CartaEditor>
```
The md I am using is:
```
**a simple list**
* item 1
* item 2
* item 3
'''    <---backticks
let y=0
$: ({tt}=data
'''     <--- also backticks
```
With the paragraph above, the bold text does show up as bold, and the code block is formatted with a dark font. 
I am using `"carta-md": "^3.4.0"` and when I first installed it, I got an error to the effect that `carta was not found` so I also `npm i carta`. Not sure if that's part of the problem

**Comment by BearToCode** [comment]
Hi @jobidon!

There should be no style in the default stylesheets for that. Probably the ones you are using aren't applying correctly.
[Here](https://www.sveltelab.dev/87vadf3qg0wimq7?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte) is a simple REPL with what you are trying to achieve, but here is basically what I did:

```svelte
<script>
	import { Carta, CartaEditor } from 'carta-md';

	import 'carta-md/default.css'; /* Default theme */
	import 'carta-md/dark.css'; /* Input theme */
	
	const carta = new Carta();

	const markdown = `
**a simple list**
* item 1
* item 2
* item 3

\`\`\`
let y=0
$: ({tt}=data
\`\`\`
	 `
</script>

<CartaEditor {carta} value={markdown} />

<style>
	:global(.markdown-body li) {
		list-style: disc;
		/* list-style: square; */ /* Try changing this for example, the style should change */
	}
</style>
```

Also, if you don't know already, you can use your [browser developer tools](https://firefox-source-docs.mozilla.org/devtools-user/) to see what styles are being apply and where they come from.

Anyway, the `carta` package is not part this package. Probably you just had to refresh the page.

Let me know if you need any more help.

**Comment by jobidon** [comment]
Thanks for your reply!
looks like in my test project, the tailwind css part of skeleton UI is preventing some styles from applying correctly.
I can override the styles with `:global(...)` like you recommended, but I need to investigate further to figure out how to prevent this in the first place.
Thanks for your input: it helped me figure out the cause, and find a solution for it

**Comment by BearToCode** [comment]
Glad to hear that! Have a nice day!

**Comment by wiseman** [comment]
I'm running into the same issue with tailwind css. Did anyone actually find a solution?

**Comment by BearToCode** [comment]
> I'm running into the same issue with tailwind css. Did anyone actually find a solution?

Hi, did you try using a separate stylesheet? You cannot apply tailwind styles directly, but you can try using the [@apply](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) directive.
