### ISSUE TITLE
Sanitizer potential broken?

### ISSUE THREAD

**Issue by benzon** [BearToCode/carta#38]
Just installed lates version of sveltekit with tailwind, and it looks like i am having some issue with the basic example you provide for sanitizers, it straight out throws an error.

app.js:16 ReferenceError: global is not defined
    at node_modules/.pnpm/isomorphic-dompurify@2.4.0/node_modules/isomorphic-dompurify/index.js (isomorphic-dompurify.js?v=697f9b3c:135780:22)
    at __require2 (chunk-US62FMVV.js?v=697f9b3c:17:50)
    at isomorphic-dompurify.js?v=697f9b3c:135786:16

**Comment by BearToCode** [comment]
You're right, it seems something changed in the latests `isomorphic-dompurify` that broke importing it that way. The new syntax is:

```ts
import DOMPurify from 'isomorphic-dompurify';

const carta = new Carta({
  sanitizer: DOMPurify.sanitize
})
```

I'll update the docs, thanks for reporting that
