### ISSUE TITLE
Explore others mechanisms to handle hiding icons on small device

### ISSUE THREAD

**Issue by SkipDead** [BearToCode/carta#42]
Hi,

First thank you for this amazing tool that is Carta. I really love your simple approach for a markdown Editor. I got easily lost on milkdown and your lib was doing exactly what I needed for my app.

I spotted a strange behavior while I was implementing your lib onto my UI.

Current behavior : 
 As the commit [hide icons on small devices](https://github.com/BearToCode/carta/commit/840bead0965ba95fd3711454b743eec05695240f) goal was to hide the icon on small device (such as small screen or mobile screen), the condition for checking the width of screen to hide or not the icons may have been incorrectly used.

https://github.com/BearToCode/carta/blob/a36b57f0c423c17bbe1500f2a243d1f1376e43d3/packages/carta-md/src/lib/CartaEditor.svelte#L101

the bind:clientWidth will actually give you the width of the div, and not the screen. If it was intentional, the following behavior happens when we voluntary wants the editor to have a smaller width on a wide screen : 

Screenshot of the width of the div just before its limit : 
![image](https://github.com/BearToCode/carta/assets/25327656/7c3f52c0-3216-4cca-87e2-e3a7381d3cfd)

Screenshot when the width is below the threshold : 
![image](https://github.com/BearToCode/carta/assets/25327656/00d5e51f-eb37-4605-8503-e2a79f7908d4)

As shown above, in a screen where the editor could easily display the icons, it will hide it because of the current threshold : 
https://github.com/BearToCode/carta/blob/a36b57f0c423c17bbe1500f2a243d1f1376e43d3/packages/carta-md/src/lib/CartaEditor.svelte#L35-L39

option 1 : If it was intentional to hide the icons depending on the div width and not the width screen : 
To not disrupt the current implemented behavior, I was thinking of allowing the dev to inject is own function to hideIcons, and having the current behavior as its default one. It will not disrupt current implementations and also enable new ones to changes its behavior 
I was thinking of maybe allowing an option to enable the dev to put is own condition to hide the icons. 

option 2 : If the goal was to currently check the window width : 
We could also implement the option 1, but we should fix the width source form the div to actually the window width.

I will try during the week to come up with a possible design solution for that.

Thanks again for this amazing lib !

**Comment by BearToCode** [comment]
Hi!
First of all thanks for the kind works, I'm glad you like the editor.

I designed the icons to be hidden when the editor size is below a certain threshold, and it works as expected. However, I must admit this is not actually a great solution, as all the icons just suddenly disappear, maybe when there is also some space to display all of them.

I propose this solution, which is also what is implemented by GitHub: display all icons that fit in the editor. Then, take those that do not fit, if any, and add them inside an additional dialog avaiable next to the icons. This way, all icons are always available, and there is no sudden transition from having all icons and not being any.

When all icons fit it's just like this:
![all-icons-fit](https://github.com/BearToCode/carta/assets/47280851/fb793c43-e944-44c5-a843-8b0926f89a1f)

When some icons do not fit it's like this:
![not-all-icons-fit](https://github.com/BearToCode/carta/assets/47280851/f075b0a6-7ddd-4b47-9530-4c1a6ab9b0c6)

Let me know what you think!

**Comment by BearToCode** [comment]
Ehy, I decided to just implement the menu immediately. I meant to preview it on a different branch but I accidentally pushed it to the master branch, and it got published... Still, [see if you like it](https://beartocode.github.io/carta/examples) (try resizing the editor)
