### ISSUE TITLE
How to use svelte reactivity in custom plugin

### ISSUE THREAD

**Issue by vlrevolution** [BearToCode/carta#43]
Is this doable? 
Kind of like being able to use svelte component as a plugin.

Another library that I've been using but it's blocking the main thread during parse. This library uses .svelte as plugins:
https://github.com/ssssota/svelte-exmarkdown

Would be cool to share info how I could render svelte components as plugin elements of diff parsed elements.  My use case is mainly for images. Ibwant to render a lightbox component that relies on store for loading state. Any idea if this is easy to support? 

Many thanks for this amazing library.

**Comment by BearToCode** [comment]
Hi, this is not super easy but is duable. I think you can do the following:
1. Create a Marked extension that renders a placeholder for the component
2. [After every render](https://beartocode.github.io/carta/api/extension#listeners) you can query-select all you placeholders and use them as targets to [mount you elements](https://svelte.dev/docs/client-side-component-api#creating-a-component).

I did something similar with the tikz-plugin (but it did not involve mounting an element):
https://github.com/BearToCode/carta/blob/b7fecea206b87ba1690410758fe19a2cf89084ba/packages/plugin-tikz/src/index.ts#L39-L55

**Comment by BearToCode** [comment]
It's been a while... I'l close this for now. Reach out if you need other help!
