### ISSUE TITLE
`plugin-attachment`: Paste support.

### ISSUE THREAD

**Issue by evwltrs** [BearToCode/carta#45]
I think it could be a really useful feature to allow a user to just paste in an image into the editor, and it becomes attached, similar to how GitHub does it. 

`HTMLElement`s paste event could be used for this.

**Comment by BearToCode** [comment]
Good idea, I'm currently working on a major update for the editor. Once that is out, I'll check this out. If you want, you can implement it yourself in the meantime, as it should be straightforward.
