### ISSUE TITLE
adding custom buttons to carta md

### ISSUE THREAD

**Issue by cruzanstx** [BearToCode/carta#52]
Is there an exposed method for adding additional buttons to the menu buttons of carta? I'm thinking of adding a dedicated save button but could see a use for adding other custom buttons by maybe passing in the icon and callback function. Is this capability exposed somewhere?

**Comment by BearToCode** [comment]
Hi, you need to add icons to a plugin. Check the docs [here](https://beartocode.github.io/carta/api/extension#icons). The `component` prop is just the SvelteComponent imported from the Svelte file.

**Comment by cruzanstx** [comment]
Will give this a shot later today, thanks for the quick response sir!

**Comment by BearToCode** [comment]
I'll close this for know, let me know if you need more help
