### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'scrollWidth')

### ISSUE THREAD

**Issue by cameronjweeks** [BearToCode/carta#53]
Error on load

carta-md.js?v=7095f9a7:2455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollWidth')
    at overflowing (carta-md.js?v=7095f9a7:2455:41)
    at carta-md.js?v=7095f9a7:2456:14
    at carta-md.js?v=7095f9a7:186:32

**Comment by BearToCode** [comment]
Hello, can you provide more information as well as a minimal reproducible example? It looks like a resize event is fired before the component is mounted, which should not happen.

**Comment by WillWilli** [comment]
Hi @BearToCode 
I am also getting this error, please see this stack blitz which reproduces the error: https://stackblitz.com/edit/vitejs-vite-bgsby6?file=src%2FApp.svelte

**Comment by BearToCode** [comment]
Should be fixed now. The example is now working in `v4.1.1`
