### ISSUE TITLE
Change the background color of code section

### ISSUE THREAD

**Issue by mohit2152sharma** [BearToCode/carta#55]
Firstly, I want to thank you on putting together this great library. Secondly, I think this should be possible, but couldn't figure out a way to do so. So I am using `Markdown` to render a markdown string. The string has couple of code lines and rest of it are normal text. I want to change the background color of code lines from rest of normal lines. 

Currently it looks something like following: 

<img width="582" alt="Screenshot 2024-04-27 at 12 52 08 AM" src="https://github.com/BearToCode/carta/assets/26904579/87d8a3b3-a153-4c65-82f4-4fa68c42e6fd">

I want to change it to something like, notice the code lines have slightly grayish background which is different from rest of the lines. 
<img width="683" alt="Screenshot 2024-04-27 at 12 53 17 AM" src="https://github.com/BearToCode/carta/assets/26904579/f9d17b33-e47c-4783-89cf-def997ebe55f">

**Comment by BearToCode** [comment]
Hello, thanks for the kind words :)
If I undestand correctly, you just want to change the look of the generated HTML(of the code block in this case). You can do so easily by creating a custom stylesheet and importing it in the pages of your app that use the `<Markdown>` component. There are already full stylesheets for all possible base elements, for example GitHub uses [this](https://github.com/sindresorhus/github-markdown-css).

**Comment by mohit2152sharma** [comment]
Thanks @BearToCode , that works too.
