### ISSUE TITLE
How to install remark/rehype plugin?

### ISSUE THREAD

**Issue by leonwang908** [BearToCode/carta#60]
https://github.com/BearToCode/carta/issues/20
looks like usage in this link is not suitable for carta 4, and I got a bit confused on official document. can you give me an example?

here is my code and it's not working at all.
```ts
<script lang="ts">
	import { Carta, MarkdownEditor } from 'carta-md';
	import type { UnifiedTransformer } from 'carta-md';
	import rehypeExternalLinks from 'rehype-external-links';
	import { code } from '@cartamd/plugin-code';

	import '$lib/styles/github.scss'; /* Default theme */

	const newlines = {
		breaks: true
	};

	const externalLinksTransformer = (): UnifiedTransformer<'sync'> => ({
		execution: 'sync',
		type: 'rehype',
		transform: ({ processor }) => {
			processor.use(rehypeExternalLinks, {
				target: '_blank',
				rel: ['noopener', 'noreferrer']
			});
		}
	});

	const carta = new Carta({
		extensions: [newlines, externalLinksTransformer]
	});

	export let value = '';
</script>
```

**Comment by BearToCode** [comment]
Hello, try with the following:

```svelte
<script lang="ts">
	import { Carta } from 'carta-md';
	import type { Plugin, UnifiedTransformer } from 'carta-md';
	import rehypeExternalLinks from 'rehype-external-links';

	import '$lib/styles/github.scss'; /* Default theme */

	const externalLinksTransformer: UnifiedTransformer<'sync'> = {
		execution: 'sync',
		type: 'rehype',
		transform: ({ processor }) => {
			processor.use(rehypeExternalLinks, {
				target: '_blank',
				rel: ['noopener', 'noreferrer']
			});
		}
	};

	const externalLinks = (): Plugin => ({
		transformers: [externalLinksTransformer]
	})

	const carta = new Carta({
		sanitizer: false,
		extensions: [externalLinks()]
	});
</script>
```

**Comment by leonwang908** [comment]
This one works, thank you!

for the `break: true` stuff, where should I set it?

**Comment by BearToCode** [comment]
Can you explain what you want to achieve with:
```ts
const newlines = {
  breaks: true
};
```

**Comment by leonwang908** [comment]
I am trying to enable new line by enter key. In default setting remark will disable it.
https://github.com/BearToCode/carta/issues/20

I assumed remark is like markdown-it can set like 
```js
new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true,
)}
```

**Comment by BearToCode** [comment]
You need to use a dedicated plugin for it: [remark-breaks](https://github.com/remarkjs/remark-breaks)

**Comment by BearToCode** [comment]
In the old version of Carta another parser was used. It has now been updated to a syntax-tree based parser, which is a combination of Unified, Remark and Rehype. From a user point of view, it should be the same

**Comment by leonwang908** [comment]
understand, thank you!

**Comment by JonL1** [comment]
Just adding this as reference for the next one.

If you add a sanitizer like DOMPurify just now that it will remove the target attribute as it's considered unsafe by default. 

You will need to allow the target attribute to the configuration options.

```javascript
const carta = new Carta({
	sanitizer: (dirty) => DOMPurify.sanitize(dirty, { ADD_ATTR: ['target'] }),
	extensions: [externalLinks()]
});
```

Make sure you are also using `rel: ['noopener', 'noreferrer']` for security and privacy.

```javascript
transform: ({ processor }) => {
		processor.use(rehypeExternalLinks, {
			target: '_blank',
			rel: ['noopener', 'noreferrer']
		});
	}
```

More info: https://github.com/cure53/DOMPurify/issues/317
