### ISSUE TITLE
theme setting in code() is not working well

### ISSUE THREAD

**Issue by leonwang908** [BearToCode/carta#61]
if there are no theme setting like `theme: 'github-light'`, code will be highlighter. but if include theme setting in code(). all code will be rendering as normal code block without highlight.

```ts
<script lang="ts">
	import { Carta, MarkdownEditor } from 'carta-md';
	import { code } from '@cartamd/plugin-code';

	import './github.scss';

	const carta = new Carta({
		sanitizer: false,
		extensions: [
			code({
				theme: 'github-light',
				langs: ['html', 'js', 'ts', 'python', 'ruby', 'php', 'java', 'c', 'csharp', 'cpp', 'css', 'sql', 'swift', 'go', 'kotlin', 'rust', 'bash', 'scala', 'julia', 'powershell', 'json', 'xml', 'yaml', 'latex', 'r', 'dart']
			})
		]
	});

	export let value = `This is an example inspired by [GitHub](https://github.com)
\`\`\`js
console.log('Hello, World!');
\`\`\`

\`\`\`python
def sum(a, b):
	return a + b
\`\`\`

`;
</script>

<MarkdownEditor bind:value mode="tabs" theme="github" {carta} />

<style>
	:global(.shiki),
	:global(.shiki span) {
		color: var(--shiki-dark) !important;
	}

	:global(button) {
		background: transparent;
		border: 0;
	}
</style>

```

![image](https://github.com/BearToCode/carta/assets/15900133/d58ab034-1f5b-4309-9c1d-81ee5bddb58d)

**Comment by leonwang908** [comment]
btw, setting of 'langs' looks like ingored
![image](https://github.com/BearToCode/carta/assets/15900133/cfbb0a81-ac28-4665-9f7c-014bdbb2e57b)

**Comment by leonwang908** [comment]
solved, thank you very much! I super love you editor, if there are more detail document it will be very helpful.

btw, just wondering. I thought only language set in langs will be rendering, but looks like all language will be render in some rule?

**Comment by leonwang908** [comment]
![image](https://github.com/BearToCode/carta/assets/15900133/9b8aa4a5-8369-4d29-8a6e-7e5f4184128e)

Hello, there is the issue that setting of langs is ingored.
when build project it will create a lot of huge js that no needed. it will decrease loading speed.

**Comment by BearToCode** [comment]
Don't worry, those languages are _bundled_ into the output directory. This does not mean they are automatically imported with the editor. In fact, if you go to your editor and start using an additional language while having the network tab open, you'll see that languages is _imported_ only when needed.

![image](https://github.com/BearToCode/carta/assets/47280851/a9bf76c5-5b2b-447f-9a5c-af7305619ece)
