### ISSUE TITLE
Markdown renderer doesn't update on value change

### ISSUE THREAD

**Issue by davidcann** [BearToCode/carta#68]
When simply displaying a value using the Markdown tag, the output doesn't render when the value variable is set. Shouldn't it update when the value changes?

Here's a simple example demonstration:

```
<script>
	import { Carta, Markdown } from "carta-md";
	const carta = new Carta();
	let value = "asdf";
</script>

Plain (updates correctly): {value} 
<hr />
<Markdown {carta} {value} />
<button on:click={() => value += " x"}>Click</button>

```

**Comment by BearToCode** [comment]
The `Markdown` component does not support values update. However, you can make it reactive with the following:
```svelte
{#key value}
  <Markdown {carta} {value} />
{/key}
```

**Comment by davidcann** [comment]
Ok, thanks!
