### ISSUE TITLE
Easier 'Read Only' mode

### ISSUE THREAD

**Issue by WillWilli** [BearToCode/carta#69]
It would be nice if there was an easier way to use the markdown viewer in a 'read-only' mode, or what you have termed 'preview' mode.

It seems like it always starts in 'write' mode and you have to click 'preview' to get to preview mode. Im not seeing an easy way to start it in 'preview' mode and just hide those tabs entirely, unless I'm missing something.

Really cool project though :D Thanks!

**Comment by WillWilli** [comment]
Looking at the code, it seems like this would be pretty easy to do by just exporting `selectedTab` in MarkdownEditor.svelte. Would you be ok with that change?

**Comment by BearToCode** [comment]
Done, should be available as soon as the new release is published!

**Comment by WillWilli** [comment]
Awesome, thank you for that!
