### ISSUE TITLE
The cursor doesn't follow accurately

### ISSUE THREAD

**Issue by srav001** [BearToCode/carta#83]
When typing, the cursor lags behind and isin't aligned at the end of the sentence 

<img width="608" alt="Screenshot 2024-06-19 at 4 04 43 PM" src="https://github.com/BearToCode/carta/assets/53465522/728151ba-2873-4a7f-a518-8648ab5391e8">

As seen above cursor isin't at the end of the sentence as it should be. 

**Repro** - https://github.com/srav001/svelte-carta-repro

**Comment by warren-bank** [comment]
I find that this works nicely:

```html
<svelte:head>
  <!-- Fira font -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap" />
</svelte:head>

<style>
  :global(.carta-font-code),
  :global(.carta-font-code *) {
    font-family: 'Fira Code', monospace !important;
    font-variant-ligatures: normal !important;
    font-size: 1.1rem !important;
    line-height: 1.5rem !important;
  }
</style>
```

..choose whatever font you like;
the important thing is to normalize the font size and height.

**Comment by srav001** [comment]
Thank you, normalizing the font size and line height was the missing piece. 

I would suggest adding it in here - https://beartocode.github.io/carta/getting-started

Since there is possibility of skipping the step unless specifically pointed out of it importance.
