### ISSUE TITLE
[reminder] several of the plugins need (minor) updates pushed to npm

### ISSUE THREAD

**Issue by warren-bank** [BearToCode/carta#89]
I hate to be a nag, but&hellip; :smiley:

_carta-md_ has received _npm_ updates as the result of the recent flurry of activity in this monorepo, but several of the plugins that are tightly coupled to these changes aren't yet published.

[This comparison](https://github.com/BearToCode/carta/compare/carta-md-v4.2.0..carta-md-v4.3.1), of the diff between tags that sufficiently bookend these changes, indicates that the following plugins have been touched:
* plugin-code
* plugin-emoji
* plugin-math
* plugin-tikz

**Comment by BearToCode** [comment]
Done, thanks 👍
