### ISSUE TITLE
Multiline selections only add "quote" markdown to the first line

### ISSUE THREAD

**Issue by glenatron** [BearToCode/carta#95]
If I have a larger block of markdown and I want to quote a section of it, it feels intuitive that I should be able to select the block and hit the "quote" button to get it quoted, like this:
```
> This is my text
> but I have more than one line selected
> so they are all marked up as a quote.
```

But instead I only get the first line marked up:
```
> This is my text
but I have more than one line selected
and they are not marked up as a quote.
```

The "quote" button here on Github behaves in the way that I would expect:

> In that a single 
> selection permits more than
> one line be quoted.

Also Github's quotes treat newlines as newlines instead of insisting on a line break between each line of markdown, which is easier to work with if one is loading text in from somewhere else. That's not really part of this issue, though, just something I notice in using it.

**Comment by BearToCode** [comment]
That is something that needs to be fixed, thanks for pointing it out!

Regarding newlines, you can use this plugin: [remark-breaks](https://github.com/remarkjs/remark-breaks). Just wrap it in a custom extension:

```ts
const newlines: Plugin = {
  transformers: [{
    execution: 'sync',
    type: 'remark',
    transform({ processor }) {
      processor.use(remarkBreaks);
    }
  }]
};

const carta = new Carta({
  // ...
  extensions: [newlines]
});
```

Haven't tested but it should work :)

**Comment by glenatron** [comment]
The PR includes a bonus fix because it would also add the prefix again isntead of removing it when the button was pressed again. It looks like everyone involved (including me, until I figured out what was going on) was assuming that JavaScript's `String.slice()` took a number of characters to slice as the second parameter instead of an ending index!
