### ISSUE TITLE
Documentation for reactivity of <Markdown>

### ISSUE THREAD

**Issue by jkruke** [BearToCode/carta#96]
It took me quite a while to figure out how to reactively update the \<Markdown\> value until I found this comment:

https://github.com/BearToCode/carta/issues/80#issuecomment-2176844409
> 2. The \<Markdown\> component is not reactive by design. If you want to make it reactive, you should use the Svelte 
`#key` block:
> ```html
> {#key value}
>  <Markdown {value} {carta} />
> {/key}
>```

It would be nice to have some documentation explaining that Markdown is not meant to be reactive and how to realize reactivity if desired (and with mentioning performance concerns). 
This information might also be added here: https://github.com/BearToCode/carta/blob/master/packages/carta-md/src/lib/Markdown.svelte#L3

**Comment by BearToCode** [comment]
Good idea, done!
