### ISSUE TITLE
Compatibility challenges with Carta + PicoCSS

### ISSUE THREAD

**Issue by jstjoe** [BearToCode/carta#99]
First, thanks for making a great tool for the Svelte community.

I'm trying to get Carta to work with my minimal site using PicoCSS. I've managed to isolate the issues to a minimal example using only Svelte, PicoCSS, and Carta.

### Reproduction steps

1- I created a boilerplate Svelte app

`npm create svelte@latest my-app`

2- Installed Carta & Pico

`npm install @picocss/pico`  `npm i carta-md`

3- Edited the example from Carta's README to include Pico:

```
<script lang="ts">
	import { Carta, MarkdownEditor } from 'carta-md';
	// Component default theme
	import 'carta-md/default.css';
        import '@picocss/pico';

	const carta = new Carta({
            sanitizer: false
	});
</script>

<MarkdownEditor {carta} />

<style>
	/* Or in global stylesheet */
	/* Set your monospace font (Required to have the editor working correctly!) */
	:global(.carta-font-code) {
		font-family: '...', monospace;
		font-size: 1.1rem;
	}
</style>
```

4- This is the result: 
<img width="1511" alt="Screenshot 2024-07-05 at 8 35 44 PM" src="https://github.com/BearToCode/carta/assets/2015604/08136066-f4b5-40c4-9667-33cc2ac65210">

### Problems:

- Cursor position is shifted.
- Text selection is shifted.
- Scroll position is shifted?
- Toolbar buttons aren't visible.

Would it be possible to add a clearfix to the Carta components so that they don't inherit any styles from the parent app? Or maybe a Pico clearfix or compatibility mode? I hate to ask for something framework-specific but I don't know know what the _correct_ fix is.

**Comment by jstjoe** [comment]
Also I'm happy to help contribute something with some direction. Thanks again.

**Comment by BearToCode** [comment]
I tried out the example and by using the following rules it works as expected:

```css
.carta-highlight code {
  padding: 0;
  box-shadow: none;
}

.carta-input textarea:focus {
  box-shadow: none;
}

.carta-icon {
  padding: 0;
}
```

Let me know if it is enough

**Comment by jstjoe** [comment]
It's aligned at the top of a document, but gets misaligned further down the document.

<img width="143" alt="Screenshot 2024-07-07 at 6 19 54 PM" src="https://github.com/BearToCode/carta/assets/2015604/7ca91783-eb23-4a6a-8292-8956eab26146">

Also the toolbar is still invisible.

<img width="1181" alt="Screenshot 2024-07-07 at 6 19 30 PM" src="https://github.com/BearToCode/carta/assets/2015604/9b2cd66a-f2d3-4051-9376-b31544846e8a">

I think a much more reliable fix would be to clear all inherited styles from the component, no? I'll be happy if it starts working but I'm concerned about other conflicting styles. It'd be great to know that there won't be any conflicts.

**Comment by BearToCode** [comment]
Did you specify a font here?
```svelte
<style>
	/* Or in global stylesheet */
	/* Set your monospace font (Required to have the editor working correctly!) */
	:global(.carta-font-code) {
		font-family: '...', monospace;
		font-size: 1.1rem;
	}
</style>
```

To me the toolbar icons are working correctly.

How would you prevent the styles from being inherited? I don't think that would work since how would you know which styles are "wrong" (like the one from pico) and which one are purposely set? Also, I would have to specify a lot of `unset` or `none` styles that are most likely useless.

I think that pico is kind of a unique problem, as, from what I understand, it already sets default styles for all HTML tags. Usually css libraries/frameworks do not come with embedded rules.

**Comment by jstjoe** [comment]
Could you maybe provide an option so that when initializing the Component I
can say “all: initial”? Then the component just needs to set the same.

That should avoid the problems you mentioned. And that way we can know that
the Component isn’t relying on - or conflicting with - any inherited styles.

Re: Pico being a unique problem, honestly that’s more of a philosophical
question. But there are lots of camps on either side. The more recent trend
is to put style information (see Tailwind) in the class names and “pollute”
the markup but that runs counter to the original intent of separating
semantic markup from style/presentation concerns. Of course there are valid
concerns on either side.

**Comment by BearToCode** [comment]
Ok, so I tried using `all: initial` but it's not working that well: setting it for everything(`.carta-editor *`) breaks certain styles, but not doing so does basically anything.

Honestly I think the best course of action is to just determine which rules from Pico causes issues by inspecting the broken elements, and manually fix them.

If you manage to find a working to make that work or have any other idea just tell me.

**Comment by warren-bank** [comment]
https://github.com/picocss/pico/issues/378

https://picocss.com/docs/conditional

**Comment by jstjoe** [comment]
I appreciate you both looking into it. I switched to Pico Conditional as you suggested, and manually added the Pico class to all of the other elements. The icons are back (yay) but the text selection and cursor is still completely off making it unusable. IDK what else to do here. I'll close it out but my issue is unresolved :/

**Comment by jstjoe** [comment]
FWIW, I don't need syntax highlighting so if you could offer a way to disable that it might be the workaround I need. Cheers.

**Comment by jstjoe** [comment]
Wait I figured it out. Conditional Pico got me close, but even Conditional Pico includes some root styles.

All I need to fix this is to set `line-height: initial;` as a style on the .carta-editor element. See screenshots for the difference. Everything else is the boilerplate from the readme.

<img width="1374" alt="Screenshot 2024-08-01 at 12 35 34 AM" src="https://github.com/user-attachments/assets/7ddef6c9-32f7-4668-a8ff-860237df095f">
<img width="1235" alt="Screenshot 2024-08-01 at 12 35 52 AM" src="https://github.com/user-attachments/assets/fd741cd9-e58e-43da-aac9-8d3712ff906c">

I don't think there's a way for me to set the style directly on the component though? I'd really rather not apply it via CSS, can you make an option to pass style props or does that exist already?

**Comment by BearToCode** [comment]
Probably adding `line-height` here does the trick:
```css
:global(.carta-font-code) {
	font-family: '...', monospace;
	font-size: 1.1rem;
	line-height: 1.25rem;
}
```
Let me know!

**Comment by jstjoe** [comment]
Got the line height working, thank you.
Now the next challenge: I can't seem to set the caret color to be compatible with pico's dark mode. This is driving me crazy.

Here's my CSS where I tried the drastic !important with no luck:

```
:global(.carta-editor) {
		line-height: initial !important;
    caret-color: white !important;
	}
```

But that is being overridden somehow? I always thought `!important` was the nuclear option but alas it's still black. How to override caret-color to make Carta work with dark mode?

<img width="417" alt="Screenshot 2024-08-15 at 11 31 12 PM" src="https://github.com/user-attachments/assets/8e816d0d-116f-4970-ae04-371123f02d0e">

**Comment by BearToCode** [comment]
From the screenshot the caret color comes from the default theme. You just need to copy the theme and edit it!
